name: Shell Commands

on:
  schedule:
    - cron: '* * * * *'
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev*'
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo astring
        run: echo "hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
